Updated django version to 3.2.17
uktrade/directory-cms pull request #1065
Opened 2023-02-17 16:36 UTC by LuptonM

To do (delete all that do not apply):

 - [ ] Change has a jira ticket that has the correct status.
 - [ ] Changelog entry added.
 - [ ] (if there are vulnerable requirements) Upgraded any vulnerable dependencies.
 - [ ] (if updating requirements) Requirements have been compiled.
 - [ ] (if adding env vars) Added any new environment variable to vault.
 - [ ] (if adding feature flags) Cleaned up old flags

2023-02-20 11:10 UTC, mforner13 commented on requirements.in
> +django==3.2.17
We agreed to upgrade to 3.2.18 instead of .17, to avoid vulnerabilities then coming up in 2.17 :)

2023-02-20 11:11 UTC, mforner13 requested changes
We agreed to upgrade to 3.2.18 instead of .17, to avoid vulnerabilities then coming up in 2.17 :)

2023-02-21 09:54 UTC, hal274 approved these changes

2023-02-21 09:57 UTC, mforner13 approved these changes

2023-02-21 09:57 UTC, merged